In [1]:
#Read File ->use pandas library for data cleaning
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("datasets/netflix.csv")

In [3]:
data

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [4]:
data.shape #rows and columns

(1000, 7)

In [5]:
data.head() #print first 5 rows

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [6]:
data.tail()   #print last 5 rows

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [7]:
data.head(n=10)  #n=10 means 10 rows and head means top rows->first 10 rows

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
6,Breaking Bad,TV-MA,For mature audiences. May not be suitable for...,110,2013,97.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
8,The Walking Dead,TV-MA,For mature audiences. May not be suitable for...,110,2015,98.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80

In [8]:
data.tail(n=10)  #last 10 rows

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
990,My Animal Friends,TV-Y,Suitable for all ages.,10,2013,NaN,82
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,41,2017,72.0,80
992,Alpha and Omega: Dino Digs,TV-G,Suitable for all ages.,35,2016,NaN,82
993,Wiener Dog Internationals,G,General Audiences. Suitable for all ages.,35,2015,NaN,82
994,Pup Star,G,General Audiences. Suitable for all ages.,35,2016,NaN,82
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [9]:
print(data.columns)

Index(['title', 'rating', 'ratingLevel', 'ratingDescription', 'release year',
       'user rating score', 'user rating size'],
      dtype='object')

In [10]:
type(data)

pandas.core.frame.DataFrame

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              1000 non-null   object
 1   rating             1000 non-null   object
 2   ratingLevel        941 non-null    object
 3   ratingDescription  1000 non-null   int64
 4   release year       1000 non-null   int64
 5   user rating score  605 non-null    float64
 6   user rating size   1000 non-null   int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.8+ KB

# PANDAS FUNCTION

LOC  #for label based selection
ILOC #for index based selection

In [12]:
data.loc[(data.rating=="PG-13") | (data["release year"]==2011)]  #use or operator means anyone from both

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
14,The Hunter,R,language and brief violence,100,2011,NaN,82
66,One Tree Hill,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,90.0,80
73,Inside Russia's Toughest Prison,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
114,Friends with Benefits,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
213,Friends with Benefits,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
250,The Waterboy,PG-13,language and some crude sexual humor,80,1998,82.0,80
251,10 Things I Hate About You,PG-13,"adult content, adult language and mild violence",80,1999,68.0,80
253,How to Lose a Guy in 10 Days,PG-13,some sex-related material,80,2003,56.0,80
254,The Benchwarmers,PG-13,"crude and suggestive humor, and for language",80,2006,77.0,80
255,Step Up,PG-13,"thematic elements, brief violence and innuendo",80,2006,64.0,80
257,Twilight,PG-13,some violence and one sexual scene,80,2008,89.0,80
273,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82
286,Safe Haven,PG-13,thematic material involving threatening behavi...,80,2013,62.0,80
300,The Waterboy,PG-13,language and some crude sexual humor,80,1998,82.0,80
302,The Wedding Planner,PG-13,language and some sexual humor,80,2001,NaN,82
306,Twilight,PG-13,some violence and one sexual scene,80,2008,89.0,80
322,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82
324,One Tree Hill,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,90.0,80
335,Trouble with the Curve,PG-13,Parents strongly cautioned. May be inappropria...,80,2012,63.0,80
372,Unconditional,PG-13,some violent content and mature thematic elements,80,2012,NaN,82
475,Forensic Files,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,88.0,80
521,Oscar's Oasis,TV-G,Suitable for all ages.,35,2011,NaN,82
523,The Adventures of Chuck & Friends,TV-Y,Suitable for all ages.,10,2011,NaN,82
569,LEGO Ninjago: Masters of Spinjitzu: Way of the...,TV-Y7-FV,Suitable for children ages 7 and older. Conte...,42,2011,NaN,82
669,DreamWorks Spooky Stories: Volume 2,TV-PG,Parental guidance suggested. May not be suitab...,70,2011,NaN,82
779,A Monster in Paris,PG,"some action violence involving gunplay, and mi...",60,2011,NaN,82
781,DreamWorks How to Train Your Dragon Legends,TV-PG,Parental guidance suggested. May not be suitab...,70,2011,NaN,82
786,PopPixie,TV-G,Suitable for all ages.,35,2011,NaN,82
818,The Little Engine That Could,G,General Audiences. Suitable for all ages.,35,2011,NaN,82
879,A Monster in Paris,PG,"some action violence involving gunplay, and mi...",60,2011,NaN,82
881,DreamWorks How to Train Your Dragon Legends,TV-PG,Parental guidance suggested. May not be suitab...,70,2011,NaN,82
886,PopPixie,TV-G,Suitable for all ages.,35,2011,NaN,82
981,Dolphin Tale,PG,some mild thematic elements,60,2011,NaN,82

In [13]:
data.loc[(data.rating=="PG-13") & (data["release year"]==2011)]  #use and operator means both true

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
273,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82
322,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82

In [14]:
data.isnull().sum()  #get info about dataset which which value is null

title                  0
rating                 0
ratingLevel           59
ratingDescription      0
release year           0
user rating score    395
user rating size       0
dtype: int64

In [15]:
data.notnull().sum()  #which column has no null values

title                1000
rating               1000
ratingLevel           941
ratingDescription    1000
release year         1000
user rating score     605
user rating size     1000
dtype: int64

In [16]:
data.loc[(data.rating=="TV-14")]  #rating is TV-14

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
...,...,...,...,...,...,...,...
489,Rosewood,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,81.0,80
491,Quantico,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,88.0,80
492,Limitless,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,84.0,80
495,No Tomorrow,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
499,Greenleaf,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,62.0,80

In [17]:
data.loc[(data.rating=="TV-14") & (data["user rating score"]>=90)]  #rating is TV-14 and rating score is 90 or above

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
...,...,...,...,...,...,...,...
472,Person of Interest,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,93.0,80
474,Scandal,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,92.0,80
476,Sherlock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
477,The Client List,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2013,92.0,80
483,The Blacklist,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80

In [18]:
data.loc[(data.rating=="TV-14"),["title","ratingLevel","ratingDescription"]] #in pandas first is row  and second is column-->separate by comma of row/column

,title,ratingLevel,ratingDescription
2,Grey's Anatomy,Parents strongly cautioned. May be unsuitable ...,90
3,Prison Break,Parents strongly cautioned. May be unsuitable ...,90
5,Supernatural,Parents strongly cautioned. May be unsuitable ...,90
7,The Vampire Diaries,Parents strongly cautioned. May be unsuitable ...,90
9,Pretty Little Liars,Parents strongly cautioned. May be unsuitable ...,90
...,...,...,...
489,Rosewood,Parents strongly cautioned. May be unsuitable ...,90
491,Quantico,Parents strongly cautioned. May be unsuitable ...,90
492,Limitless,Parents strongly cautioned. May be unsuitable ...,90
495,No Tomorrow,Parents strongly cautioned. May be unsuitable ...,90
499,Greenleaf,Parents strongly cautioned. May be unsuitable ...,90

In [19]:
data.loc[(data.rating=="TV-14"),["title","ratingLevel","ratingDescription"]].isnull().sum() #how many null values in new data

title                0
ratingLevel          9
ratingDescription    0
dtype: int64

In [20]:
data.loc[(data.rating=="TV-14"),["title","ratingLevel","ratingDescription"]].shape

(234, 3)

# PANDAS--> ILOC(INDEX BASED SELECTION)

In [21]:
data.iloc[[0,2]]

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80

In [22]:
data.iloc[[0,2],0:2]  #0,2 means 0 and 2 rows print and 0:2 for column start from 0 to 1 means first 2 column print

            title rating
0    White Chicks  PG-13
2  Grey's Anatomy  TV-14

In [23]:
data.iloc[0:3]  #start from 0 to 2 index means first 3 rows print

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80

In [24]:
data.iloc[0:3,0:-1]  #0:3 means 0 then 1 then 2 rows tk jaey and 0:-1 means start sy last tk except last column

,title,rating,ratingLevel,ratingDescription,release year,user rating score
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0

In [25]:
data.describe()

       ratingDescription  release year  user rating score  user rating size
count         1000.00000   1000.000000         605.000000       1000.000000
mean            67.36600   2010.335000          84.094215         80.783000
std             30.78561      8.877927          12.344371          0.973066
min             10.00000   1940.000000          55.000000         80.000000
25%             35.00000   2007.000000          75.000000         80.000000
50%             60.00000   2015.000000          88.000000         80.000000
75%             90.00000   2016.000000          95.000000         82.000000
max            124.00000   2017.000000          99.000000         82.000000

# ONE-HOT-ENCODING TECHNIQUE

In [26]:
data

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [27]:
data.isnull().sum()

title                  0
rating                 0
ratingLevel           59
ratingDescription      0
release year           0
user rating score    395
user rating size       0
dtype: int64

In [33]:
a=data["user rating score"].mean()  # replace null values with mean value in specified column
a

84.09421487603316

In [34]:
data.replace(to_replace=np.nan,value = a ,inplace = True) #np.nan means null value replace with value

In [35]:
data

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.000000,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,84.094215,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.000000,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.000000,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.000000,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.000000,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,84.094215,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,84.094215,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,84.094215,82
999,Growing Up Wild,G,84.094215,35,2016,80.000000,80